import { Big_Shoulders_Inline_Text } from "next/font/google";
import "./globals.css";
import BaseLayout from "./BaseLayout";

const bigShouldersInlineText = Big_Shoulders_Inline_Text({
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons: "/logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
